### ISSUE TITLE
follow duration - is it hours or minutes?

### ISSUE THREAD

**Issue by thomasmorgan** [berkeley-cocosci/Wallace#189]
we have been using it as hours, but in extending a HIT psiturk seems to use it as a minute value. Which is the correct one?

**Comment by suchow** [comment]
Looking into this now...

**Comment by suchow** [comment]
Okay, so `duration` is specified in the configuration file for each demo. It only appears in a couple other places elsewhere in the code:

1. In `PsiTurkRecruiter.open_recruitment`, which calls `PsiturkNetworkShell.hit_create`, which specifies `"duration": datetime.timedelta(hours=duration)`. Okay, so this one is hours.

2. In `PsiturkRecruiter.recruit_participants`, which contains the following:

```
            expiration_increment = self.config.get('HIT Configuration',
                                                   'duration')

            self.mtc.extend_hit(
                hit_id,
                expiration_increment=int(
                    float(expiration_increment or 0) * 3600))
```

So this multiplies `duration` by 3600 and then calls the `extend_hit` function in Boto, which contains:

```
        if expiration_increment:
            params['ExpirationIncrementInSeconds'] = expiration_increment
```

and thus expects seconds.

So everything looks okay to me.

@thomasmorgan, is the behavior incorrect?

**Comment by thomasmorgan** [comment]
Nope, looks good to me. Feel free to close.

--
Thomas J. H. Morgan
Assistant Professor of Evolutionary Anthropology
Arizona State University



www.eccolab.org
