### ISSUE TITLE
clock dyno is always performance M

### ISSUE THREAD

**Issue by thomasmorgan** [berkeley-cocosci/Wallace#365]
it should be linked to the config file

**Comment by suchow** [comment]
As part of this, we should figure out how to make it possible to run Wallace on the free tier. They allow only 1 web and 1 worker, which means that we'll have to forgo use of the clock process in instances where the web and worker dyno are set to free tier. That can be accomplished be overwriting the Procfile.

**Comment by suchow** [comment]
Closed by #408.
