### ISSUE TITLE
network_type() does not work

### ISSUE THREAD

**Issue by thomasmorgan** [berkeley-cocosci/Wallace#367]
just tried running an experiment with

def network_type(self):
    return Empty

I get an error saying you can insert a class into the network table - it must be an instance of a class.

So I guess the default

def create_network(self):
    return self.network_type()()

is not working

For now I just switched to 

def create_network(self):
    return Empty()

and that worked fine, its actually so clean I wonder if we should just delete network_type()

**Comment by suchow** [comment]
Yes, your solution is a good one — people can directly override the `create_network()` function and we can delete `network_type()`. If we do this, we should consider doing the same for `create_node()` and `node_type()` for consistency.
