### ISSUE TITLE
update requirements to use psiturk branch wallace2b

### ISSUE THREAD

**Issue by thomasmorgan** [berkeley-cocosci/Wallace#394]
or merge2b into wallace2

**Comment by suchow** [comment]
What is 2b? I am currently working on improving the config files in #362, and that uses a new branch of psiTurk, `wallace3`.

**Comment by suchow** [comment]
I'm closing this because I have cherry-picked the commit from wallace2b and added it to the wallace3 branch, which will be merged with #362.
