### ISSUE TITLE
Put documentation in a more accessible location

### ISSUE THREAD

**Issue by jhamrick** [berkeley-cocosci/Wallace#411]
I would like to suggest that the docs get moved to something like readthedocs rather than having them be a combination between the wiki and the docs/ folder. Right now it is really hard for me t find what I'm looking for, and that's going to be a big problem for others as well.

Sphinx (which readthedocs uses) will automatically compile the docs for you and warn you e.g. if cross links between docs are broken. You can also install various plugins like a spellchecker, which is nice, too. That would also allow you to create API documentation.

I am happy to make a PR for this.

**Comment by suchow** [comment]
Agreed on wanting the docs to be readable. I've gotten 95% of the way to
getting the docs to build automatically on readthedocs, I'll finish doing
that this weekend in time for the tutorial. I'm going to veto Sphinx in
favor of MkDocs, because I like Markdown more than rst.

**Comment by jhamrick** [comment]
Ok, sounds good.

**Comment by suchow** [comment]
Done, docs are up at http://wallace.readthedocs.io.
