### ISSUE TITLE
Gather materials from CogSci tutorial

### ISSUE THREAD

**Issue by suchow** [berkeley-cocosci/Wallace#454]
## Session 1 (9 – 10:30 a.m.)
- [x] Overview & introductions, Jordan Suchow
- [ ] Cultural evolution and iterated learning, Tom Griffiths
- [x] Using Wallace to run an experiment, Jordan Suchow

## Session 2 (11 a.m. – noon)
- [x] Database, models, classes, Jess Hamrick
- [x] Web application & API, Mike Pacer

## Session 3 (1 – 2:30 p.m.)
- [x] Structure of an experiment package, Jess Hamrick
- [x] Deep dive into Bartlett (1932) demo, Jordan Suchow
- [x] Advanced topics, Stephan Meylan

## Session 4 (3 – 4 p.m.)
- [x] Best practices in managing participants, Stephan Meylan
- [x] Discussion, Jordan Suchow

**Comment by suchow** [comment]
[Introduction.pdf](https://github.com/berkeley-cocosci/Wallace/files/425126/Introduction.pdf)

**Comment by suchow** [comment]
[Schedule.pdf](https://github.com/berkeley-cocosci/Wallace/files/425128/Schedule.pdf)

**Comment by suchow** [comment]
[Demo.pdf](https://github.com/berkeley-cocosci/Wallace/files/425131/Demo.pdf)

**Comment by suchow** [comment]
[Deep dive.pdf](https://github.com/berkeley-cocosci/Wallace/files/425134/Deep.dive.pdf)

**Comment by suchow** [comment]
[Wallace Directory Structure.pdf](https://github.com/berkeley-cocosci/Wallace/files/428989/Wallace.Directory.Structure.pdf)

**Comment by suchow** [comment]
[Wallace Classes.pdf](https://github.com/berkeley-cocosci/Wallace/files/428990/Wallace.Classes.pdf)

**Comment by suchow** [comment]
[cogsci_2016_tutorial.pdf](https://github.com/berkeley-cocosci/Wallace/files/428993/cogsci_2016_tutorial.pdf)

**Comment by suchow** [comment]
[cogsci_2016_workers.pdf](https://github.com/berkeley-cocosci/Wallace/files/428994/cogsci_2016_workers.pdf)

**Comment by michaelpacer** [comment]
[cogsci_2016_Wallace_App_and_API.pdf](https://github.com/berkeley-cocosci/Wallace/files/430793/cogsci_2016_Wallace_App_and_API.pdf)

**Comment by suchow** [comment]
Still missing Tom's but sent them out anyways...
