### ISSUE TITLE
Create proper documentation

### ISSUE THREAD

**Issue by jhamrick** [berkeley-cocosci/Wallace#8]
For now we should just use the wiki for documentation, but eventually (in the distant future) it would be nice to have real documentation with something like Sphinx. Here's another project I've done that has Sphinx documentation:

http://jhamrick.github.io/gaussian_processes/

The reason why I like Sphinx is that it allows you to hyperlink between classes and objects, and lets you create really general pages of documentation (that don't have to be API documentation necessarily). Also, you can include arbitrary content like math and images (though I guess you can probably do that in a wiki as well).

We can set up the documentation using GitHub pages, so it doesn't require anything except an extra branch in the repository.

**Comment by suchow** [comment]
Closed by #399.

**Comment by suchow** [comment]
Reopening this and assigning to @jhamrick, who offered to move us over to Sphinx for nice API documentation.

**Comment by suchow** [comment]
@jhamrick Just wanted to check in on this — are we still making the jump to Sphinx?
