### ISSUE TITLE
Publish to Pypi

### ISSUE THREAD

**Issue by suchow** [berkeley-cocosci/Wallace#98]
https://pypi.python.org/pypi

(Don't do this until it's 1.0 and ready to be shared publicly, though.)

**Comment by suchow** [comment]
I'm having some trouble getting this to work.

**Comment by suchow** [comment]
This seems worth fixing, but I don't really have any good ideas. Right now what's blocking is that giving psiTurk as a `-e` dependency won't automatically install it. My first thought was to upload our custom version of psiTurk to PyPi, but I couldn't get `psiturk-wallace` to install correctly after uploading it.

@jhamrick Can you remind me what you had recommended?

**Comment by jhamrick** [comment]
From my email:

> I'm not sure if you can specify eggs as dependencies on pypi. Actually, I don't think pypi actually uses the requirements file at all -- I believe it does the installation just with the setup.py. So I think if the installation doesn't work correctly with setup.py alone (without the `pip install -r requirements.txt`), it won't work correctly from pypi. If you need the requirements.txt file (e.g. for readthedocs) you can just have it have a single line with `-e .` (see https://caremad.io/2013/07/setup-vs-requirement/)
>
> I *think* one thing that's missing from your setup.py is to specify both install_requires *and* dependency_links for psiTurk. But also, stackoverflow seems to suggest that that's not enough: http://stackoverflow.com/questions/12518499/pip-ignores-dependency-links-in-setup-py
>
> You can hack it if you specify an exact version (and that version doesn't conflict with the psiTurk already in pypi) and you can also use --process-dependency-links with pip. But apparently that's deprecated and going to be removed soon.

I'm not sure why you would have trouble with psiturk-wallace -- in principle I think that should work.

**Comment by jhamrick** [comment]
Which is the repo you're publishing `psiturk-wallace` from? I can have a look at it to figure out why it's not working...

**Comment by jhamrick** [comment]
Nevermind, that's a stupid question because I can just look at the dependency link 😉

**Comment by jhamrick** [comment]
Ok, I think the issue is that you need to include a `include requirements.txt` in the MANIFEST.in for your copy of psiTurk.

**Comment by suchow** [comment]
Okay, that worked, thanks — `psiturk-wallace` is installable from PyPi. I created a [`pypi` branch](https://github.com/berkeley-cocosci/Wallace/tree/pypi) here to test this out as a dependency, but haven't yet.

**Comment by suchow** [comment]
Done! Closed by #479.
